[package]
name = "impulse"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
generational-arena = "0.2.8"

[dev-dependencies]
kiss3d = "0.28.0"
nalgebra = "0.23.2"